### ISSUE TITLE
Dependency download fails with Go version 1.12

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpbackup-s3-plugin#11]
This is presumably the same as issue https://github.com/greenplum-db/gpbackup/issues/326

Dependency download fails with Go version 1.12.7

```
go mod download
warning: pattern "all" matched no module dependencies
go build -tags 'gpbackup_s3_plugin' -o /tmp/s3plugin/bin/gpbackup_s3_plugin -ldflags "-X github.com/greenplum-db/gpbackup-s3-plugin/s3plugin.Version=1.2.0+dev.3.g51d8dbc"
# github.com/greenplum-db/gpbackup-s3-plugin
./gpbackup_s3_plugin.go:15:18: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in assignment:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
./gpbackup_s3_plugin.go:23:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
./gpbackup_s3_plugin.go:66:4: cannot use s3plugin.GetAPIVersion (type func(*cli.Context)) as type cli.ActionFunc in field value
Makefile:42: recipe for target 'build' failed
make: *** [build] Error 2
```

Dependency download works with Go Version 1.13.4

**Comment by baileygm** [comment]
I tried setting GO111MODULE=on as a temporary fix but get an error
```
go: finding github.com/greenplum-db/gpbackup-s3-plugin/... latest
go: finding github.com/greenplum-db/gpbackup-s3-plugin latest
go: downloading github.com/greenplum-db/gpbackup-s3-plugin v0.0.0-20191212192250-51d8dbc031e8
go: extracting github.com/greenplum-db/gpbackup-s3-plugin v0.0.0-20191212192250-51d8dbc031e8
go get github.com/greenplum-db/gpbackup-s3-plugin/...: no matching versions for query "latest"
```

**Comment by baileygm** [comment]
The code compiles OK now with Go 1.12 after the latest commit, thanks

**Comment by kyeap-pivotal** [comment]
Fixed with commit 807b2bb843d9fe9cf6c0663d6e257a75c695d58a
